[general]
import = ["~/.config/alacritty/tokyonight_night.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[terminal]
shell = "/bin/zsh"

[window]
dynamic_title = true

[window.padding]
x = 5
y = 5
